version: "3.9"

services:
  db:
    image: timescale/timescaledb:2.13.1-pg15
    container_name: crypto-timescale
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - crypto_pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=timescaledb
      -c max_connections=200
      -c work_mem=64MB
      -c maintenance_work_mem=256MB

volumes:
  crypto_pgdata: